---
services:
  restful-api:
    build: .
    container_name: restful_api
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/api
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
