---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      initContainers:
        - name: init-db-file
          image: busybox
          command:
            - /bin/sh
            - -c
          args:
            - |
              touch /mnt/data/sqlite-storage/db.sqlite3 && \
              chown 1000:1000 /mnt/data/sqlite-storage/db.sqlite3 && \
              chmod 660 /mnt/data/sqlite-storage/db.sqlite3
          volumeMounts:
            - name: sqlite-storage-dir
              mountPath: /mnt/data/sqlite-storage
      containers:
        - name: demo-app
          image: ghcr.io/OWNER/REPO:TAG
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sqlite-storage-dir
              mountPath: /app/db.sqlite3
              subPath: db.sqlite3
          env:
            - name: DATABASE_NAME
              value: db.sqlite3
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: django-secret-key
          readinessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: sqlite-storage-dir
          persistentVolumeClaim:
            claimName: sqlite-pvc
