---
name: Build and Tests
on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: demo.settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tag name from triggering workflow
        run: |
          TAG_NAME="${{ github.event.workflow_run.head_branch }}"
          if [[ "$TAG_NAME" =~ ^v[0-9] ]]; then
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          else
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up environment variables
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "DATABASE_NAME=db.sqlite3" >> .env
      - name: Run makemigrations
        run: python manage.py makemigrations
      - name: Run migrate
        run: python manage.py migrate
      - name: Run tests
        run: |
          python manage.py test api
